version: '3.8'

services:
  postgres:
    container_name: spring_batch
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_batch
    ports:
      - "54325:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres_network:
    name: postgres_network
    driver: bridge